const gallery = {
  apartment: ['/images/two-bedroom.png', '/images/apartment-kitchen.png', '/images/apartment-bedroom.png', '/images/shared-apartment.png'],
  home: ['/images/one-bedroom.png', '/images/apartment-kitchen.png', '/images/apartment-bedroom.png', '/images/two-bedroom.png'],
  land: ['/images/land-roadside.png', '/images/land-sunset.png', '/images/land-frontage.png', '/images/land-roadside.png'],
}

const listings = [
  { id: 1, purpose: 'Rent', title: 'Bright two-bedroom apartment', township: 'Hlaing', address: 'Insein Road, Hlaing Township, Yangon', price: 450000, beds: 2, baths: 1, sqft: 920, type: 'Apartment', built: 2018, image: '/images/two-bedroom.png', images: gallery.apartment, description: 'A bright, move-in-ready apartment with an open living area, practical kitchen and easy access to shops, schools and public transport.', features: ['Generator backup', 'Pet friendly', 'Wi-Fi ready', 'Near shops'] },
  { id: 2, purpose: 'Rent', title: 'Quiet one-bedroom home', township: 'Sanchaung', address: 'Baho Road, Sanchaung Township, Yangon', price: 360000, beds: 1, baths: 1, sqft: 650, type: 'Apartment', built: 2016, image: '/images/one-bedroom.png', images: gallery.home, description: 'A calm one-bedroom home tucked into a convenient Sanchaung neighbourhood, with comfortable living space and excellent everyday connections.', features: ['Air conditioning', '24/7 security', 'Quiet street', 'Furnished'] },
  { id: 3, purpose: 'Rent', title: 'Affordable shared apartment', township: 'Kamayut', address: 'Hledan Road, Kamayut Township, Yangon', price: 250000, beds: 1, baths: 1, sqft: 540, type: 'Shared home', built: 2014, image: '/images/shared-apartment.png', images: gallery.apartment, description: 'A budget-friendly shared home close to Hledan, universities and transit, ideal for students and young professionals.', features: ['Shared kitchen', 'Furnished room', 'Near bus stop', 'Utilities ready'] },
  { id: 4, purpose: 'Buy', title: 'Family home near YBS routes', township: 'Yankin', address: 'Thitsar Road, Yankin Township, Yangon', price: 175000000, beds: 3, baths: 2, sqft: 1850, type: 'House', built: 2012, image: '/images/two-bedroom.png', images: gallery.home, description: 'A welcoming family home with generous rooms, a private outdoor area and quick access to major YBS routes and neighbourhood services.', features: ['Car parking', 'Private garden', 'Backup water', 'Near YBS routes'] },
  { id: 5, purpose: 'Buy', title: 'Modern city apartment', township: 'Bahan', address: 'Kabar Aye Pagoda Road, Bahan Township, Yangon', price: 120000000, beds: 2, baths: 2, sqft: 1120, type: 'Apartment', built: 2020, image: '/images/one-bedroom.png', images: gallery.apartment, description: 'A modern two-bedroom city apartment with a clean contemporary finish, secure entry and a central Bahan location.', features: ['Lift access', '24/7 security', 'Modern kitchen', 'Car parking'] },
  { id: 6, purpose: 'Land', title: 'Residential land near main road', township: 'North Dagon', address: 'Pinlon Road, North Dagon Township, Yangon', price: 95000000, beds: 0, baths: 0, sqft: 2400, type: 'Land', built: null, image: '/images/land-roadside.png', images: gallery.land, description: 'Well-positioned residential land with straightforward main-road access and strong potential for a new family home or long-term investment.', features: ['Residential zoning', 'Road access', 'Electricity nearby', 'Clear boundary'] },
]

export default listings
